# Generated by Django 5.2.7 on 2025-11-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='number',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
