# Generated by Django 5.2.7 on 2025-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_tj', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='teachers/videos/')),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_tj', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_language_ru', models.CharField(max_length=255)),
                ('english_language_en', models.CharField(max_length=255)),
                ('english_language_tj', models.CharField(max_length=255)),
                ('online_ru', models.TextField()),
                ('online_en', models.TextField()),
                ('online_tj', models.TextField()),
                ('from_990_ru', models.CharField(max_length=50)),
                ('from_990_en', models.CharField(max_length=50)),
                ('from_990_tj', models.CharField(max_length=50)),
                ('we_monitor_ru', models.TextField()),
                ('we_monitor_en', models.TextField()),
                ('we_monitor_tj', models.TextField()),
                ('change_goals_ru', models.TextField()),
                ('change_goals_en', models.TextField()),
                ('change_goals_tj', models.TextField()),
                ('select_tutor_ru', models.CharField(max_length=100)),
                ('select_tutor_en', models.CharField(max_length=100)),
                ('select_tutor_tj', models.CharField(max_length=100)),
                ('teachers', models.ManyToManyField(related_name='pages', to='teacher_page.teacher')),
            ],
        ),
    ]
