# Generated by Django 5.2.7 on 2025-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ru', models.TextField(blank=True)),
                ('en', models.TextField(blank=True)),
                ('tj', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroTitle_ru', models.CharField(max_length=255)),
                ('heroTitle_en', models.CharField(max_length=255)),
                ('heroTitle_tj', models.CharField(max_length=255)),
                ('heroSubtitle_ru', models.CharField(max_length=255)),
                ('heroSubtitle_en', models.CharField(max_length=255)),
                ('heroSubtitle_tj', models.CharField(max_length=255)),
                ('heroDescription_ru', models.CharField(max_length=255)),
                ('heroDescription_en', models.CharField(max_length=255)),
                ('heroDescription_tj', models.CharField(max_length=255)),
                ('howItWorksTitle_ru', models.CharField(max_length=255)),
                ('howItWorksTitle_en', models.CharField(max_length=255)),
                ('howItWorksTitle_tj', models.CharField(max_length=255)),
                ('levelsTitle_ru', models.CharField(max_length=255)),
                ('levelsTitle_en', models.CharField(max_length=255)),
                ('levelsTitle_tj', models.CharField(max_length=255)),
                ('levelsDescription_ru', models.TextField()),
                ('levelsDescription_en', models.TextField()),
                ('levelsDescription_tj', models.TextField()),
                ('steps', models.ManyToManyField(to='content.step')),
            ],
        ),
    ]
