# Generated by Django 5.2.7 on 2025-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField()),
                ('question_ru', models.TextField()),
                ('question_tj', models.TextField()),
                ('answer_en', models.TextField()),
                ('answer_ru', models.TextField()),
                ('answer_tj', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VacancyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_tj', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_tj', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_tj', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vacancy/')),
            ],
        ),
    ]
