# Generated by Django 5.2.7 on 2026-01-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='stat',
            name='order',
        ),
        migrations.AlterField(
            model_name='stat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
