# Generated by Django 5.2.7 on 2025-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=10)),
                ('dateCompleted', models.DateTimeField(blank=True, null=True)),
                ('timeSpent', models.CharField(blank=True, max_length=50, null=True)),
                ('totalQuestions', models.IntegerField()),
                ('correctAnswers', models.IntegerField(blank=True, null=True)),
                ('incorrectAnswers', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], max_length=20)),
            ],
        ),
    ]
