# Generated by Django 5.2.7 on 2025-12-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_testadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAdmin',
        ),
    ]
