# Generated by Django 5.2.7 on 2025-12-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_delete_testadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pdf_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
