# Generated by Django 5.2.7 on 2025-12-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_userprofile_is_pdf_userprofile_pdf_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
