# Generated by Django 5.2.7 on 2025-12-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0006_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
