# Generated by Django 5.2.7 on 2025-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
