# Generated by Django 5.2.7 on 2025-12-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0009_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
