# Generated by Django 5.2.7 on 2025-12-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0010_notificationadmin_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
