# Generated by Django 5.2.7 on 2025-12-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0012_smscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password')], default='register', max_length=20),
        ),
    ]
