# Generated by Django 5.2.7 on 2025-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0013_smscode_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password'), ('notification', 'Notification')], default='register', max_length=20),
        ),
    ]
