# Generated by Django 5.2.7 on 2025-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField()),
                ('question_ru', models.TextField()),
                ('question_tj', models.TextField()),
                ('answer_en', models.TextField()),
                ('answer_ru', models.TextField()),
                ('answer_tj', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FaqText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_tj', models.CharField(max_length=255)),
                ('faqDescription_en', models.TextField()),
                ('faqDescription_ru', models.TextField()),
                ('faqDescription_tj', models.TextField()),
                ('addQuestion_en', models.CharField(max_length=255)),
                ('addQuestion_ru', models.CharField(max_length=255)),
                ('addQuestion_tj', models.CharField(max_length=255)),
                ('addTitle_en', models.CharField(max_length=255)),
                ('addTitle_ru', models.CharField(max_length=255)),
                ('addTitle_tj', models.CharField(max_length=255)),
                ('editTitle_en', models.CharField(max_length=255)),
                ('editTitle_ru', models.CharField(max_length=255)),
                ('editTitle_tj', models.CharField(max_length=255)),
                ('cancel_en', models.CharField(max_length=255)),
                ('cancel_ru', models.CharField(max_length=255)),
                ('cancel_tj', models.CharField(max_length=255)),
                ('save_en', models.CharField(max_length=255)),
                ('save_ru', models.CharField(max_length=255)),
                ('save_tj', models.CharField(max_length=255)),
                ('add_en', models.CharField(max_length=255)),
                ('add_ru', models.CharField(max_length=255)),
                ('add_tj', models.CharField(max_length=255)),
                ('confirmDelete_en', models.CharField(max_length=255)),
                ('confirmDelete_ru', models.CharField(max_length=255)),
                ('confirmDelete_tj', models.CharField(max_length=255)),
            ],
        ),
    ]
