# Generated by Django 5.2.7 on 2025-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('iframe', models.TextField(blank=True)),
                ('hours', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
