# Generated by Django 5.2.7 on 2025-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_tj', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_tj', models.TextField(blank=True)),
                ('duration_ru', models.CharField(blank=True, max_length=255)),
                ('duration_en', models.CharField(blank=True, max_length=255)),
                ('duration_tj', models.CharField(blank=True, max_length=255)),
                ('academic_support_ru', models.CharField(blank=True, max_length=255)),
                ('academic_support_en', models.CharField(blank=True, max_length=255)),
                ('academic_support_tj', models.CharField(blank=True, max_length=255)),
                ('clubs_ru', models.CharField(blank=True, max_length=255)),
                ('clubs_en', models.CharField(blank=True, max_length=255)),
                ('clubs_tj', models.CharField(blank=True, max_length=255)),
                ('level_ru', models.CharField(blank=True, max_length=255)),
                ('level_en', models.CharField(blank=True, max_length=255)),
                ('level_tj', models.CharField(blank=True, max_length=255)),
                ('type_ru', models.CharField(blank=True, max_length=255)),
                ('type_en', models.CharField(blank=True, max_length=255)),
                ('type_tj', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSchoolCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_tj', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_tj', models.TextField(blank=True)),
                ('duration_ru', models.CharField(blank=True, max_length=255)),
                ('duration_en', models.CharField(blank=True, max_length=255)),
                ('duration_tj', models.CharField(blank=True, max_length=255)),
                ('academic_support_ru', models.CharField(blank=True, max_length=255)),
                ('academic_support_en', models.CharField(blank=True, max_length=255)),
                ('academic_support_tj', models.CharField(blank=True, max_length=255)),
                ('clubs_ru', models.CharField(blank=True, max_length=255)),
                ('clubs_en', models.CharField(blank=True, max_length=255)),
                ('clubs_tj', models.CharField(blank=True, max_length=255)),
                ('level_ru', models.CharField(blank=True, max_length=255)),
                ('level_en', models.CharField(blank=True, max_length=255)),
                ('level_tj', models.CharField(blank=True, max_length=255)),
                ('type_ru', models.CharField(blank=True, max_length=255)),
                ('type_en', models.CharField(blank=True, max_length=255)),
                ('type_tj', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subject_ru', models.TextField(blank=True)),
                ('subject_en', models.TextField(blank=True)),
                ('subject_tj', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RussianCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_tj', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_tj', models.TextField(blank=True)),
                ('duration_ru', models.CharField(blank=True, max_length=255)),
                ('duration_en', models.CharField(blank=True, max_length=255)),
                ('duration_tj', models.CharField(blank=True, max_length=255)),
                ('academic_support_ru', models.CharField(blank=True, max_length=255)),
                ('academic_support_en', models.CharField(blank=True, max_length=255)),
                ('academic_support_tj', models.CharField(blank=True, max_length=255)),
                ('clubs_ru', models.CharField(blank=True, max_length=255)),
                ('clubs_en', models.CharField(blank=True, max_length=255)),
                ('clubs_tj', models.CharField(blank=True, max_length=255)),
                ('level_ru', models.CharField(blank=True, max_length=255)),
                ('level_en', models.CharField(blank=True, max_length=255)),
                ('level_tj', models.CharField(blank=True, max_length=255)),
                ('type_ru', models.CharField(blank=True, max_length=255)),
                ('type_en', models.CharField(blank=True, max_length=255)),
                ('type_tj', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
