# Generated by Django 5.2.7 on 2025-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishcourse',
            name='subject_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='englishcourse',
            name='subject_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='englishcourse',
            name='subject_tj',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='russiancourse',
            name='subject_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='russiancourse',
            name='subject_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='russiancourse',
            name='subject_tj',
            field=models.TextField(blank=True),
        ),
    ]
