# Generated by Django 5.2.7 on 2025-12-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
