# Generated by Django 5.2.7 on 2025-12-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testresult_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='answers',
        ),
    ]
