# Generated by Django 5.2.7 on 2025-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_testresult_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
